### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-1-infografia-Kevinosorio77#1]
[Infografia Kevin Andrew Osorio Aparicio (1).pdf](https://github.com/user-attachments/files/16821107/Infografia.Kevin.Andrew.Osorio.Aparicio.1.pdf)

**Comment by edgarmauricio123** [comment]
18% Tiene una falta de ortografía y de igual manera o es con todas las letras mayúsculas o con todas minúsculas.

**Comment by josealfredo79** [comment]
bien hecho y revisado...
